### ISSUE TITLE
Custom event does not trigger callback in browser

### ISSUE THREAD

**Issue by flerro** [smaldini/grails-events-push#13]
Using:
    - grails-platform-core 1.0.M3
    - grails-events-push 1.0.M2-SNAPSHOT

In my project I experienced that the browser receive the event triggered by a Controller, but the bound javascript callback does not seem to be fired.

I have uploaded a sample and detailed the issue at:

   https://github.com/flerro/events-push-sample/

**Comment by smaldini** [comment]
Thank you for such a complete test case, downloading it and testing.

On Tue, Aug 14, 2012 at 6:13 PM, flerro notifications@github.com wrote:

> Using:
> - grails-platform-core 1.0.M3
> - grails-events-push 1.0.M2-SNAPSHOT
> 
> In my project I experienced that the browser receive the event triggered
> by a Controller, but the bound javascript callback does not seem to be
> fired.
> 
> I have uploaded a sample and detailed the issue at:
> 
> https://github.com/flerro/events-push-sample/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/13.

## 

## _Stéphane MALDINI_

**Comment by smaldini** [comment]
Spotted,
You need an Event DSL in your conf to authorize this topic (or authorize a
wildcard topic)
1/ add grails-app/conf/MyEvents.groovy:
2/ inside :
  events = {
     bagsUpdated browser:true
  }

3/ there is a breaking change, which I'm currently questioning:
-- remove for:'browser" in your event call (the last snapshot now defaults
to app topic, my bad)
OR
-- add the namespace in the DSL ->    bagsUpdated browser:true,
namespace:'browser'
The plugin will automatically detect the namespace param in your definition
and give it to the client-side listener

4/ refresh

PS: the first message will be fixed in the final version of Atmosphere.

On Tue, Aug 14, 2012 at 6:35 PM, Stephane Maldini <
stephane.maldini@gmail.com> wrote:

> Thank you for such a complete test case, downloading it and testing.
> 
> On Tue, Aug 14, 2012 at 6:13 PM, flerro notifications@github.com wrote:
> 
> > Using:
> > - grails-platform-core 1.0.M3
> > - grails-events-push 1.0.M2-SNAPSHOT
> > 
> > In my project I experienced that the browser receive the event triggered
> > by a Controller, but the bound javascript callback does not seem to be
> > fired.
> > 
> > I have uploaded a sample and detailed the issue at:
> > 
> > https://github.com/flerro/events-push-sample/
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/13.
> 
> ## 
> 
> _Stéphane MALDINI_
>  --

## 

## _Stéphane MALDINI_
